export interface OllamaModelEntry {
  name: string;
  description: string;
  sizes?: string[];
}

export interface OllamaModelCategory {
  id: string;
  label: string;
  icon: string;
  description: string;
  models: OllamaModelEntry[];
}

export const OLLAMA_CATEGORIES: OllamaModelCategory[] = [
  {
    id: 'top-picks',
    label: 'Top Picks',
    icon: '🏆',
    description: 'Most popular and recommended models',
    models: [
      { name: 'llama3.3', description: 'Latest Llama, strong all-rounder', sizes: ['70b'] },
      { name: 'llama3.1:8b', description: 'Best balance of speed & quality', sizes: ['8b'] },
      { name: 'llama3.1:70b', description: 'High-quality general purpose', sizes: ['70b'] },
      { name: 'qwen2.5:7b', description: 'Strong multilingual model', sizes: ['7b'] },
      { name: 'qwen2.5:32b', description: 'Excellent reasoning & coding', sizes: ['32b'] },
      { name: 'deepseek-r1:8b', description: 'Top reasoning model (distilled)', sizes: ['8b'] },
      { name: 'deepseek-r1:14b', description: 'Strong reasoning, good speed', sizes: ['14b'] },
      { name: 'mistral-nemo', description: '12B model from Mistral, very capable', sizes: ['12b'] },
      { name: 'gemma2:9b', description: 'Google Gemma 2, efficient & smart', sizes: ['9b'] },
      { name: 'qwen2.5-coder:7b', description: 'Best coding model overall', sizes: ['7b'] },
    ],
  },
  {
    id: 'llm',
    label: 'Large Language Models',
    icon: '🧠',
    description: 'General-purpose LLMs for chat & tasks',
    models: [
      { name: 'llama3.3', description: 'Meta Llama 3.3, top-tier all-rounder', sizes: ['70b'] },
      { name: 'llama3.2:3b', description: 'Lightweight Llama 3.2', sizes: ['3b'] },
      { name: 'llama3.1:8b', description: 'Llama 3.1 8B — great quality/speed', sizes: ['8b'] },
      { name: 'llama3.1:70b', description: 'Llama 3.1 70B — high quality', sizes: ['70b'] },
      { name: 'llama3.1:405b', description: 'Full-size Llama 3.1 405B', sizes: ['405b'] },
      { name: 'llama3:8b', description: 'Llama 3 8B', sizes: ['8b'] },
      { name: 'llama3:70b', description: 'Llama 3 70B', sizes: ['70b'] },
      { name: 'llama2:7b', description: 'Llama 2 7B', sizes: ['7b'] },
      { name: 'llama2:13b', description: 'Llama 2 13B', sizes: ['13b'] },
      { name: 'llama2:70b', description: 'Llama 2 70B', sizes: ['70b'] },
      { name: 'llama2-uncensored:7b', description: 'Uncensored Llama 2', sizes: ['7b'] },
      { name: 'qwen2.5:0.5b', description: 'Qwen 2.5 tiny', sizes: ['0.5b'] },
      { name: 'qwen2.5:1.5b', description: 'Qwen 2.5 small', sizes: ['1.5b'] },
      { name: 'qwen2.5:3b', description: 'Qwen 2.5 3B', sizes: ['3b'] },
      { name: 'qwen2.5:7b', description: 'Qwen 2.5 7B — strong all-rounder', sizes: ['7b'] },
      { name: 'qwen2.5:14b', description: 'Qwen 2.5 14B', sizes: ['14b'] },
      { name: 'qwen2.5:32b', description: 'Qwen 2.5 32B — excellent reasoning', sizes: ['32b'] },
      { name: 'qwen2.5:72b', description: 'Qwen 2.5 72B', sizes: ['72b'] },
      { name: 'qwen2:7b', description: 'Qwen 2 7B', sizes: ['7b'] },
      { name: 'mistral', description: 'Mistral 7B, fast & capable', sizes: ['7b'] },
      { name: 'mistral-nemo', description: 'Mistral Nemo 12B', sizes: ['12b'] },
      { name: 'mixtral', description: 'Mixtral 8x7B MoE', sizes: ['47b'] },
      { name: 'mixtral8x22b', description: 'Mixtral 8x22B MoE', sizes: ['141b'] },
      { name: 'gemma2:2b', description: 'Google Gemma 2 2B, tiny but capable', sizes: ['2b'] },
      { name: 'gemma2:9b', description: 'Google Gemma 2 9B', sizes: ['9b'] },
      { name: 'gemma2:27b', description: 'Google Gemma 2 27B', sizes: ['27b'] },
      { name: 'phi3:3.8b', description: 'Microsoft Phi-3 3.8B', sizes: ['3.8b'] },
      { name: 'phi3:14b', description: 'Microsoft Phi-3 14B', sizes: ['14b'] },
      { name: 'phi3.5', description: 'Microsoft Phi-3.5 3.8B', sizes: ['3.8b'] },
      { name: 'command-r', description: 'Cohere Command R 35B', sizes: ['35b'] },
      { name: 'command-r-plus', description: 'Cohere Command R+ 104B', sizes: ['104b'] },
      { name: 'dbrx', description: 'Databricks DBRX 132B', sizes: ['132b'] },
      { name: 'falcon:7b', description: 'Falcon 7B', sizes: ['7b'] },
      { name: 'falcon:40b', description: 'Falcon 40B', sizes: ['40b'] },
      { name: 'falcon2', description: 'Falcon 2 11B', sizes: ['11b'] },
      { name: 'solar', description: 'Solar 10.7B', sizes: ['10.7b'] },
      { name: 'yi:6b', description: 'Yi 6B', sizes: ['6b'] },
      { name: 'yi:34b', description: 'Yi 34B', sizes: ['34b'] },
      { name: 'aya', description: 'Aya 23, multilingual (8B/35B)', sizes: ['8b', '35b'] },
      { name: 'tulu3', description: 'Tulu 3, instruction-tuned', sizes: ['8b', '70b'] },
      { name: 'olmo2', description: 'OLMo 2, open language model', sizes: ['7b', '13b'] },
      { name: 'olmoe', description: 'OLMoE, mixture of experts', sizes: ['1b'] },
      { name: 'granite3-dense', description: 'IBM Granite 3 dense', sizes: ['1b', '3b', '8b'] },
      { name: 'granite3.1-dense', description: 'IBM Granite 3.1 dense', sizes: ['2b', '8b'] },
      { name: 'smollm2', description: 'HuggingFace SmolLM2 (135M–14B)', sizes: ['135m', '360m', '1.7b', '14b'] },
      { name: 'stablelm2', description: 'Stable LM 2 (1.6B/12B)', sizes: ['1.6b', '12b'] },
      { name: 'nemotron', description: 'NVIDIA Nemotron 4 340B', sizes: ['340b'] },
    ],
  },
  {
    id: 'coding',
    label: 'Coding',
    icon: '💻',
    description: 'Models optimized for code generation & completion',
    models: [
      { name: 'qwen2.5-coder:1.5b', description: 'Qwen Coder 1.5B, tiny code model', sizes: ['1.5b'] },
      { name: 'qwen2.5-coder:7b', description: 'Best coding model, strong at all languages', sizes: ['7b'] },
      { name: 'qwen2.5-coder:14b', description: 'Qwen Coder 14B', sizes: ['14b'] },
      { name: 'qwen2.5-coder:32b', description: 'Qwen Coder 32B, top-tier coding', sizes: ['32b'] },
      { name: 'deepseek-coder-v2', description: 'DeepSeek Coder V2, excellent at code', sizes: ['16b', '236b'] },
      { name: 'deepseek-llm:7b', description: 'DeepSeek LLM 7B', sizes: ['7b'] },
      { name: 'deepseek-llm:67b', description: 'DeepSeek LLM 67B', sizes: ['67b'] },
      { name: 'codegemma:2b', description: 'Google CodeGemma 2B, fast code completion', sizes: ['2b'] },
      { name: 'codegemma:7b', description: 'Google CodeGemma 7B', sizes: ['7b'] },
      { name: 'codellama:7b', description: 'Code Llama 7B', sizes: ['7b'] },
      { name: 'codellama:13b', description: 'Code Llama 13B', sizes: ['13b'] },
      { name: 'codellama:34b', description: 'Code Llama 34B', sizes: ['34b'] },
      { name: 'starcoder2:3b', description: 'StarCoder2 3B', sizes: ['3b'] },
      { name: 'starcoder2:7b', description: 'StarCoder2 7B', sizes: ['7b'] },
      { name: 'starcoder2:15b', description: 'StarCoder2 15B', sizes: ['15b'] },
      { name: 'granite-code:3b', description: 'IBM Granite Code 3B', sizes: ['3b'] },
      { name: 'granite-code:8b', description: 'IBM Granite Code 8B', sizes: ['8b'] },
      { name: 'granite-code:34b', description: 'IBM Granite Code 34B', sizes: ['34b'] },
      { name: 'wizardcoder:7b', description: 'WizardCoder 7B', sizes: ['7b'] },
      { name: 'wizardcoder:13b', description: 'WizardCoder 13B', sizes: ['13b'] },
      { name: 'wizardcoder:34b', description: 'WizardCoder 34B', sizes: ['34b'] },
      { name: 'olympiccoder', description: 'Olympic Coder, sports programming focus', sizes: ['7b'] },
      { name: 'stable-code', description: 'Stable Code 3B', sizes: ['3b'] },
      { name: 'falcoder', description: 'Falcon Coder 7B', sizes: ['7b'] },
    ],
  },
  {
    id: 'reasoning',
    label: 'Reasoning',
    icon: '🔍',
    description: 'Deep reasoning & chain-of-thought models',
    models: [
      { name: 'deepseek-r1:1.5b', description: 'Distilled R1 1.5B, tiny reasoning', sizes: ['1.5b'] },
      { name: 'deepseek-r1:7b', description: 'DeepSeek-R1 distilled 7B', sizes: ['7b'] },
      { name: 'deepseek-r1:8b', description: 'DeepSeek-R1 distilled 8B', sizes: ['8b'] },
      { name: 'deepseek-r1:14b', description: 'DeepSeek-R1 distilled 14B, great balance', sizes: ['14b'] },
      { name: 'deepseek-r1:32b', description: 'DeepSeek-R1 distilled 32B', sizes: ['32b'] },
      { name: 'deepseek-r1:70b', description: 'DeepSeek-R1 distilled 70B', sizes: ['70b'] },
      { name: 'deepseek-r1:671b', description: 'DeepSeek-R1 full 671B (MoE)', sizes: ['671b'] },
      { name: 'qwq', description: 'QwQ 32B, strong reasoning from Qwen team', sizes: ['32b'] },
      { name: 'deepseek-v3', description: 'DeepSeek V3 671B (MoE), very strong', sizes: ['671b'] },
      { name: 'mathstral', description: 'Mathstral 7B, math-focused reasoning', sizes: ['7b'] },
    ],
  },
  {
    id: 'vision',
    label: 'Vision / Multimodal',
    icon: '👁️',
    description: 'Models that understand images & video',
    models: [
      { name: 'llama3.2-vision:11b', description: 'Llama 3.2 Vision 11B', sizes: ['11b'] },
      { name: 'llama3.2-vision:90b', description: 'Llama 3.2 Vision 90B', sizes: ['90b'] },
      { name: 'qwen2.5vl:3b', description: 'Qwen 2.5 VL 3B, vision-language', sizes: ['3b'] },
      { name: 'qwen2.5vl:7b', description: 'Qwen 2.5 VL 7B', sizes: ['7b'] },
      { name: 'qwen2.5vl:72b', description: 'Qwen 2.5 VL 72B', sizes: ['72b'] },
      { name: 'llava:7b', description: 'LLaVA 7B', sizes: ['7b'] },
      { name: 'llava:13b', description: 'LLaVA 13B', sizes: ['13b'] },
      { name: 'llava:34b', description: 'LLaVA 34B', sizes: ['34b'] },
      { name: 'llava-llama3', description: 'LLaVA-Llama3 8B', sizes: ['8b'] },
      { name: 'llava-phi3', description: 'LLaVA-Phi3 3.8B', sizes: ['3.8b'] },
      { name: 'bakllava:7b', description: 'BakLLaVA 7B', sizes: ['7b'] },
      { name: 'bakllava:13b', description: 'BakLLaVA 13B', sizes: ['13b'] },
      { name: 'moondream', description: 'Moondream 2 1.8B, tiny vision model', sizes: ['1.8b'] },
      { name: 'minicpm-v', description: 'MiniCPM-V 8B, strong vision-language', sizes: ['8b'] },
      { name: 'internvl2', description: 'InternVL2 8B vision-language', sizes: ['8b'] },
      { name: 'ovis1.6', description: 'Ovis 1.6 vision-language', sizes: ['8b'] },
      { name: 'granite3-vision', description: 'Granite 3 Vision 8B', sizes: ['8b'] },
    ],
  },
  {
    id: 'math',
    label: 'Math & Science',
    icon: '📐',
    description: 'Models specialized for math, science & reasoning',
    models: [
      { name: 'qwen2.5-math:1.5b', description: 'Qwen 2.5 Math 1.5B', sizes: ['1.5b'] },
      { name: 'qwen2.5-math:7b', description: 'Qwen 2.5 Math 7B', sizes: ['7b'] },
      { name: 'mathstral', description: 'Mathstral 7B, Mistral fine-tuned for math', sizes: ['7b'] },
      { name: 'wizardmath:7b', description: 'WizardMath 7B', sizes: ['7b'] },
      { name: 'wizardmath:13b', description: 'WizardMath 13B', sizes: ['13b'] },
      { name: 'wizardmath:70b', description: 'WizardMath 70B', sizes: ['70b'] },
      { name: 'meditron:7b', description: 'Meditron 7B, medical knowledge', sizes: ['7b'] },
      { name: 'meditron:70b', description: 'Meditron 70B', sizes: ['70b'] },
    ],
  },
  {
    id: 'small',
    label: 'Small & Fast',
    icon: '⚡',
    description: 'Sub-4B models for speed & low RAM',
    models: [
      { name: 'llama3.2:1b', description: 'Llama 3.2 1B, extremely fast', sizes: ['1b'] },
      { name: 'llama3.2:3b', description: 'Llama 3.2 3B, fast & capable', sizes: ['3b'] },
      { name: 'qwen2.5:0.5b', description: 'Qwen 2.5 0.5B, tiny', sizes: ['0.5b'] },
      { name: 'qwen2.5:1.5b', description: 'Qwen 2.5 1.5B', sizes: ['1.5b'] },
      { name: 'qwen2.5-coder:1.5b', description: 'Qwen Coder 1.5B', sizes: ['1.5b'] },
      { name: 'phi3:3.8b', description: 'Phi-3 3.8B, surprisingly capable', sizes: ['3.8b'] },
      { name: 'phi3.5', description: 'Phi-3.5 3.8B', sizes: ['3.8b'] },
      { name: 'gemma2:2b', description: 'Gemma 2 2B', sizes: ['2b'] },
      { name: 'tinyllama', description: 'TinyLlama 1.1B', sizes: ['1.1b'] },
      { name: 'smollm2:135m', description: 'SmolLM2 135M, smallest usable LLM', sizes: ['135m'] },
      { name: 'smollm2:360m', description: 'SmolLM2 360M', sizes: ['360m'] },
      { name: 'smollm2:1.7b', description: 'SmolLM2 1.7B', sizes: ['1.7b'] },
      { name: 'stablelm2:1.6b', description: 'Stable LM 2 1.6B', sizes: ['1.6b'] },
      { name: 'dolphin-phi', description: 'Dolphin Phi 2.7B', sizes: ['2.7b'] },
      { name: 'moondream', description: 'Moondream 2 1.8B vision', sizes: ['1.8b'] },
      { name: 'granite3-dense:1b', description: 'Granite 3 1B', sizes: ['1b'] },
      { name: 'granite3-dense:3b', description: 'Granite 3 3B', sizes: ['3b'] },
      { name: 'starcoder2:3b', description: 'StarCoder2 3B code model', sizes: ['3b'] },
      { name: 'codegemma:2b', description: 'CodeGemma 2B, fast code completion', sizes: ['2b'] },
    ],
  },
  {
    id: 'embedding',
    label: 'Embedding',
    icon: '🔢',
    description: 'Models for text embeddings & RAG',
    models: [
      { name: 'nomic-embed-text', description: 'Nomic Embed Text, best general embedding', sizes: ['v1'] },
      { name: 'mxbai-embed-large', description: 'Mxbai Embed Large, high quality', sizes: ['v1'] },
      { name: 'all-minilm', description: 'All-MiniLM-L6-v2, small & fast', sizes: ['v2'] },
      { name: 'snowflake-arctic-embed', description: 'Snowflake Arctic Embed', sizes: ['v1'] },
      { name: 'snowflake-arctic-embed2', description: 'Snowflake Arctic Embed 2', sizes: ['v2'] },
      { name: 'bge-m3', description: 'BGE M3, multilingual', sizes: ['v1'] },
      { name: 'bge-large', description: 'BGE Large, high quality Chinese/English', sizes: ['v1'] },
      { name: 'jina-embeddings-v2-base-en', description: 'Jina Embeddings v2, English', sizes: ['v2'] },
      { name: 'snowflake-arctic-embed:l', description: 'Large Arctic Embed (sbert alias)', sizes: ['l'] },
    ],
  },
  {
    id: 'instruct',
    label: 'Instruction / Chat',
    icon: '💬',
    description: 'Fine-tuned chat & instruction-following models',
    models: [
      { name: 'openchat', description: 'OpenChat 7B, strong chat model', sizes: ['7b'] },
      { name: 'openhermes', description: 'OpenHermes 2.5, Mistral fine-tune', sizes: ['7b'] },
      { name: 'zephyr', description: 'Zephyr 7B, aligned chat model', sizes: ['7b'] },
      { name: 'neural-chat', description: 'Neural Chat 7B, Intel fine-tune', sizes: ['7b'] },
      { name: 'nous-hermes2', description: 'Nous Hermes 2, Mistral/Llama fine-tune', sizes: ['7b', '34b'] },
      { name: 'starling-lm', description: 'Starling LM 7B, RLHF-tuned chat', sizes: ['7b'] },
      { name: 'dolphin-llama3', description: 'Dolphin Llama 3 8B', sizes: ['8b'] },
      { name: 'dolphin-mistral', description: 'Dolphin Mistral 7B', sizes: ['7b'] },
      { name: 'vicuna:7b', description: 'Vicuna 7B', sizes: ['7b'] },
      { name: 'vicuna:13b', description: 'Vicuna 13B', sizes: ['13b'] },
      { name: 'vicuna:33b', description: 'Vicuna 33B', sizes: ['33b'] },
      { name: 'orca-mini:3b', description: 'Orca Mini 3B', sizes: ['3b'] },
      { name: 'orca-mini:7b', description: 'Orca Mini 7B', sizes: ['7b'] },
      { name: 'orca-mini:13b', description: 'Orca Mini 13B', sizes: ['13b'] },
      { name: 'stable-beluga:7b', description: 'Stable Beluga 7B', sizes: ['7b'] },
      { name: 'stable-beluga:13b', description: 'Stable Beluga 13B', sizes: ['13b'] },
      { name: 'stable-beluga:70b', description: 'Stable Beluga 70B', sizes: ['70b'] },
      { name: 'wizardlm2:7b', description: 'Wizard LM 2 7B', sizes: ['7b'] },
      { name: 'wizardlm2:8x22b', description: 'Wizard LM 2 8x22B MoE', sizes: ['141b'] },
      { name: 'everythinglm', description: 'EverythingLM 13B', sizes: ['13b'] },
    ],
  },
  {
    id: 'community',
    label: 'Community & Niche',
    icon: '🌐',
    description: 'Community uploads, merges & niche models',
    models: [
      { name: 'nexusraven', description: 'Nexus Raven, function-calling specialist', sizes: ['7b', '13b'] },
      { name: 'alfrebe', description: 'Alfrebe 7B', sizes: ['7b'] },
      { name: 'hippogriff', description: 'Hippogriff, story-writing', sizes: ['7b-70b'] },
      { name: 'arcee', description: 'Arcee, fine-tuned for chat', sizes: ['7b'] },
      { name: 'os-atlas', description: 'OS Atlas, code understanding', sizes: ['7b'] },
      { name: 'glm4', description: 'GLM 4, bilingual Chinese/English', sizes: ['9b'] },
      { name: 'aquila', description: 'Aquila 7B, bilingual', sizes: ['7b'] },
      { name: 'ministral', description: 'Ministral 8B, Mistral small', sizes: ['8b'] },
      { name: 'ministral3b', description: 'Ministral 3B, tiny Mistral', sizes: ['3b'] },
    ],
  },
];

export function getModelFullName(model: OllamaModelEntry, preferredSize?: string): string {
  if (preferredSize && model.sizes?.includes(preferredSize)) {
    const [name] = model.name.split(':');
    return `${name}:${preferredSize}`;
  }
  return model.name;
}
