import { BasePlugin, PluginResult, PluginConfig } from './base';
import * as ts from 'typescript';

export class DocGeneratorPlugin extends BasePlugin {
  constructor(config?: PluginConfig) {
    super('doc-generator', 'Doc Generator', config);
  }

  getDescription(): string {
    return 'Generate documentation from code comments';
  }

  async run(): Promise<PluginResult> {
    try {
      const cwd = this.config?.cwd || process.cwd();
      const fs = await import('fs');
      const path = await import('path');

      const docs: Array<{ file: string; name: string; type: string; comment: string }> = [];
      const files: string[] = [];

      function walk(dir: string) {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          const full = path.join(dir, entry.name);
          if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
            walk(full);
          } else if (entry.isFile() && /\.(ts|tsx|js|jsx)$/.test(entry.name)) {
            files.push(full);
          }
        }
      }
      walk(cwd);

      for (const file of files.slice(0, 30)) {
        const source = fs.readFileSync(file, 'utf-8');
        const sourceFile = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true);

        function visit(node: ts.Node) {
          const comments = ts.getLeadingCommentRanges(source, node.pos) || [];
          const commentText = comments.map(c => source.substring(c.pos, c.end))
            .join('\n')
            .replace(/\/\*\*/g, '')
            .replace(/\*\//g, '')
            .replace(/\* ?/g, '')
            .trim();

          if (ts.isFunctionDeclaration(node) && node.name) {
            docs.push({
              file: path.relative(cwd, file),
              name: node.name.text,
              type: 'function',
              comment: commentText || 'No documentation',
            });
          }
          if (ts.isInterfaceDeclaration(node) && node.name) {
            docs.push({
              file: path.relative(cwd, file),
              name: node.name.text,
              type: 'interface',
              comment: commentText || 'No documentation',
            });
          }
          if (ts.isClassDeclaration(node) && node.name) {
            docs.push({
              file: path.relative(cwd, file),
              name: node.name.text,
              type: 'class',
              comment: commentText || 'No documentation',
            });
          }
          if (ts.isTypeAliasDeclaration(node) && node.name) {
            docs.push({
              file: path.relative(cwd, file),
              name: node.name.text,
              type: 'type',
              comment: commentText || 'No documentation',
            });
          }
          ts.forEachChild(node, visit);
        }
        visit(sourceFile);
      }

      const mdPath = path.join(cwd, 'API_REFERENCE.md');
      const md = `# API Reference\n\nGenerated by TIMPS Doc Generator\n\n${docs.map(d =>
        `## ${d.name}\n\n**Type:** ${d.type}  \n**File:** ${d.file}  \n\n${d.comment}\n`
      ).join('\n')}`;

      fs.writeFileSync(mdPath, md, 'utf-8');

      return {
        success: true,
        output: `Generated API_REFERENCE.md with ${docs.length} documented symbols`,
        data: { documented: docs.length, outputFile: 'API_REFERENCE.md' },
      };
    } catch (err: unknown) {
      return { success: false, error: err instanceof Error ? err.message : 'Doc generation failed' };
    }
  }
}
