/* eslint-disable */
// Auto-generated by NAPI-RS — do not edit manually.
export function isLlamaAvailable(): boolean
export function listLocalModels(): string
export function runInference(modelPath: string, prompt: string, maxTokens: number, temperature: number, topP: number): string
export function streamInference(modelPath: string, prompt: string, maxTokens: number, temperature: number): string
export function getModelInfo(modelPath: string): string
export function downloadModel(modelId: string, targetDir: string): string
export function readFileContext(path: string, maxLines: number): string
export function extractCodeContext(dir: string, fileLimit: number): string
export function extractCodeSnippets(dir: string, maxFiles: number): string
export function countTokens(text: string): number
export function truncateToTokens(text: string, maxTokens: number): string
export function getTextEmbedding(text: string): string
export function cosineSimilarityScores(a: string, b: string): number
export function getSystemInfo(): string
// Phase 4d: Rust-native compute engine
export function computeBatchSimilarity(vectors: number[], query: number[], count: number, dims: number): Float64Array
export function kmeansClusterFlat(embeddings: number[], count: number, dims: number, k: number, maxIter?: number): Int32Array
export function eigenmodeWarmStart(n: number, iIndices: number[], jIndices: number[], values: number[], k: number, cachedValues?: number[], cachedVectors?: number[], cachedN?: number, maxIter?: number): string
export class RustLsh {
  constructor()
  insert(id: string, content: string): void
  query(content: string, maxResults?: number): string[]
  delete(id: string): void
  size(): number
  clear(): void
  getAll(): string[]
}
