/* eslint-disable */
// Auto-generated by NAPI-RS — do not edit manually.
// Platform-detecting loader for the @timps/memory-core-rs native addon.
'use strict'

const { platform, arch } = process

let binding

const loadError = []

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return require('fs').readFileSync(lddPath, 'utf8').includes('musl')
    } catch {
      return true
    }
  }
  const { glibcVersionRuntime } = process.report.getReport().header
  return !glibcVersionRuntime
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        try { binding = require('./memory-core-rs.android-arm64.node'); break } catch (e) { loadError.push(e) }
        break
      default:
        loadError.push(new Error(`Unsupported Android arch: ${arch}`))
    }
    break
  case 'darwin':
    switch (arch) {
      case 'arm64':
        try { binding = require('./memory-core-rs.darwin-arm64.node'); break } catch (e) { loadError.push(e) }
        break
      case 'x64':
        try { binding = require('./memory-core-rs.darwin-x64.node'); break } catch (e) { loadError.push(e) }
        break
      default:
        loadError.push(new Error(`Unsupported macOS arch: ${arch}`))
    }
    break
  case 'linux':
    if (isMusl()) {
      switch (arch) {
        case 'x64':
          try { binding = require('./memory-core-rs.linux-x64-musl.node'); break } catch (e) { loadError.push(e) }
          break
        case 'arm64':
          try { binding = require('./memory-core-rs.linux-arm64-musl.node'); break } catch (e) { loadError.push(e) }
          break
        default:
          loadError.push(new Error(`Unsupported Linux musl arch: ${arch}`))
      }
    } else {
      switch (arch) {
        case 'x64':
          try { binding = require('./memory-core-rs.linux-x64-gnu.node'); break } catch (e) { loadError.push(e) }
          break
        case 'arm64':
          try { binding = require('./memory-core-rs.linux-arm64-gnu.node'); break } catch (e) { loadError.push(e) }
          break
        default:
          loadError.push(new Error(`Unsupported Linux arch: ${arch}`))
      }
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        try { binding = require('./memory-core-rs.win32-x64-msvc.node'); break } catch (e) { loadError.push(e) }
        break
      case 'arm64':
        try { binding = require('./memory-core-rs.win32-arm64-msvc.node'); break } catch (e) { loadError.push(e) }
        break
      default:
        loadError.push(new Error(`Unsupported Windows arch: ${arch}`))
    }
    break
  default:
    loadError.push(new Error(`Unsupported platform: ${platform}`))
}

if (!binding) {
  const msgs = loadError.map((e) => e.message).join('\n  ')
  throw new Error(
    `Failed to load @timps/memory-core-rs native addon.\n  ${msgs}\n\nBuild with:\n  cd packages/memory-core-rs && npm run build\n`
  )
}

module.exports = binding
