/**
 * TIMPS Desktop - Icons
 * Icon component using emoji/Unicode symbols.
 */

import './Icons.css';

type IconName = 
  | 'add'
  | 'edit'
  | 'delete'
  | 'search'
  | 'settings'
  | 'menu'
  | 'close'
  | 'back'
  | 'forward'
  | 'chevronDown'
  | 'chevronUp'
  | 'chevronLeft'
  | 'chevronRight'
  | 'check'
  | 'warning'
  | 'info'
  | 'error'
  | 'success'
  | 'loading'
  | 'home'
  | 'folder'
  | 'file'
  | 'image'
  | 'video'
  | 'audio'
  | 'code'
  | 'link'
  | 'copy'
  | 'cut'
  | 'paste'
  | 'save'
  | 'download'
  | 'upload'
  | 'refresh'
  | 'sync'
  | 'lock'
  | 'unlock'
  | 'eye'
  | 'eyeOff'
  | 'star'
  | 'starOutlined'
  | 'heart'
  | 'heartOutlined'
  | 'flag'
  | 'bell'
  | 'bellOff'
  | 'mail'
  | 'mailOpen'
  | 'calendar'
  | 'clock'
  | 'map'
  | 'location'
  | 'phone'
  | 'user'
  | 'users'
  | 'group'
  | 'chat'
  | 'comment'
  | 'share'
  | 'send'
  | 'filter'
  | 'sort'
  | 'grid'
  | 'list'
  | 'table'
  | 'chart'
  | 'barChart'
  | 'pieChart'
  | 'trendingUp'
  | 'trendingDown'
  | 'money'
  | 'cart'
  | 'tag'
  | 'tags'
  | 'bookmark'
  | 'bookmarkOutlined'
  | 'lightbulb'
  | 'bug'
  | 'tool'
  | 'wrench'
  | 'cog'
  | 'sliders'
  | 'bolt'
  | 'fire'
  | 'cloud'
  | 'cloudOff'
  | 'database'
  | 'server'
  | 'laptop'
  | 'mobile'
  | 'tablet'
  | 'wifi'
  | 'wifiOff'
  | 'power'
  | 'battery'
  | 'plug'
  | 'cursor'
  | 'drag'
  | 'move'
  | 'expand'
  | 'collapse'
  | 'fullscreen'
  | 'fullscreenExit'
  | 'zoomIn'
  | 'zoomOut'
  | 'plus'
  | 'minus'
  | 'minusCircle'
  | 'plusCircle'
  | 'help'
  | 'question'
  | 'infoCircle'
  | 'exclamationCircle';

const iconMap: Record<IconName, string> = {
  add: '+',
  edit: '✎',
  delete: '🗑',
  search: '🔍',
  settings: '⚙',
  menu: '☰',
  close: '✕',
  back: '←',
  forward: '→',
  chevronDown: '▼',
  chevronUp: '▲',
  chevronLeft: '◀',
  chevronRight: '▶',
  check: '✓',
  warning: '⚠',
  info: 'ℹ',
  error: '✕',
  success: '✓',
  loading: '...',
  home: '🏠',
  folder: '📁',
  file: '📄',
  image: '🖼',
  video: '🎬',
  audio: '🎵',
  code: '⌘',
  link: '🔗',
  copy: '📋',
  cut: '✂',
  paste: '📌',
  save: '💾',
  download: '⬇',
  upload: '⬆',
  refresh: '↻',
  sync: '⟳',
  lock: '🔒',
  unlock: '🔓',
  eye: '👁',
  eyeOff: '👁‍🗨',
  star: '★',
  starOutlined: '☆',
  heart: '♥',
  heartOutlined: '♡',
  flag: '🚩',
  bell: '🔔',
  bellOff: '🔕',
  mail: '✉',
  mailOpen: '📬',
  calendar: '📅',
  clock: '🕐',
  map: '🗺',
  location: '📍',
  phone: '📞',
  user: '👤',
  users: '👥',
  group: '👥',
  chat: '💬',
  comment: '💬',
  share: '📤',
  send: '📨',
  filter: '⚡',
  sort: '↕',
  grid: '⊞',
  list: '≡',
  table: '▦',
  chart: '📊',
  barChart: '📊',
  pieChart: '◔',
  trendingUp: '↗',
  trendingDown: '↘',
  money: '💰',
  cart: '🛒',
  tag: '🏷',
  tags: '🏷',
  bookmark: '🔖',
  bookmarkOutlined: '📑',
  lightbulb: '💡',
  bug: '🐛',
  tool: '🔧',
  wrench: '🔧',
  cog: '⚙',
  sliders: '⚙',
  bolt: '⚡',
  fire: '🔥',
  cloud: '☁',
  cloudOff: '☁',
  database: '🗄',
  server: '🖥',
  laptop: '💻',
  mobile: '📱',
  tablet: '📱',
  wifi: '📶',
  wifiOff: '📶',
  power: '⏻',
  battery: '🔋',
  plug: '🔌',
  cursor: '↖',
  drag: '⇲',
  move: '⇲',
  expand: '⤢',
  collapse: '⤡',
  fullscreen: '⛶',
  fullscreenExit: '⛶',
  zoomIn: '🔍+',
  zoomOut: '🔍-',
  plus: '+',
  minus: '−',
  minusCircle: '⊖',
  plusCircle: '⊕',
  help: '?',
  question: '?',
  infoCircle: 'ℹ',
  exclamationCircle: '⚠',
};

interface IconProps {
  name: IconName;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
  spin?: boolean;
}

export function Icon({ name, size = 'md', className = '', spin }: IconProps) {
  return (
    <span className={`icon icon-${size} ${spin ? 'icon-spin' : ''} ${className}`}>
      {iconMap[name]}
    </span>
  );
}